version: '3.9'

networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      datapipeline:
        ipv4_address: 172.18.0.3

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=172.18.0.3:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://172.18.0.4:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "29092:29092"
    restart: on-failure
    depends_on:
      - zookeeper
    networks:
      datapipeline:
        ipv4_address: 172.18.0.4

  processstream:
    image: btctothemoonz/travisnkento:0.0.2
    command: >
      bash -c "python ../volume/bin/processStream.py --topic my-stream"
    volumes:
      - '$PWD:/volume'
    ports:
      - '9042:9042'
    networks:
      datapipeline:
        ipv4_address: 172.18.0.5

  sendstream:
    image: btctothemoonz/travisnkento:0.0.2
    command: >
      bash -c "python ../volume/bin/sendStream.py --speed 10 --topic my-stream"
    volumes:
      - '$PWD:/volume' #so it turns out this line is causing the problem before. 
                      #previously, all the "home" is replaced because of the conflict in name
    ports:
      - '8080:8080'
    # depends_on:
    #   - processstream
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2


  # sendStream:
  #   # image: btctothemoonz/travisnkento
  #   build: .
  #   network_mode: "host"        
  #   env_file: .env
  #   # environment:
  #   #   - PYTHONPATH=${PYTHONPATH}
  #   volumes:
  #     - '$PWD:/home' # Maps current working directory to the /home 
  #   command: >
  #     python bin/sendStream.py data/data.csv my-stream --speed 10

  # processStream:
  #   # image: btctothemoonz/travisnkento
  #   build: .
  #   network_mode: "host"    
  #   env_file: .env
  #   environment:
  #     - PYTHONPATH=${PYTHONPATH}
  #   volumes:
  #     - '$PWD:/home' # Maps current working directory to the /home 
  #   command: >
  #     python bin/processStream.py my-stream
